In [39]:
from exactextract import exact_extract
import numpy as np
import pandas as pd

In [3]:
rast_path = r"H:\DEV\GMS\data\GC62_part\GC62_part_2023_03_21_12_20_49_prediction_treemap_classification_TEST_treemap_classification_prediction.yaml\MaskedPrediction.bsq"
polys_path = r"seg_obszar15_clip.shp"

In [7]:
result = exact_extract(rast_path, polys_path, ["majority", "frac", "coverage", "values"], output="pandas", include_cols=["gid"])

In [9]:
result

gid  majority  \
0       15320461.0      48.0   
1       15029785.0      32.0   
2       15243650.0      10.0   
3       15322602.0      23.0   
4       15321453.0      35.0   
...            ...       ...   
386954  15271767.0      31.0   
386955  15038183.0      10.0   
386956  15179203.0      10.0   
386957  15038343.0      10.0   
386958  15319521.0      48.0   

                                                     frac  \
0                                              [0.5, 0.5]   
1       [0.6666666865348816, 0.2222222238779068, 0.111...   
2       [0.06923077255487442, 0.7153846025466919, 0.02...   
3                                                   [1.0]   
4       [0.6388888955116272, 0.1666666716337204, 0.083...   
...                                                   ...   
386954  [0.022727273404598236, 0.3579545319080353, 0.0...   
386955  [0.1015625, 0.03125, 0.078125, 0.171875, 0.226...   
386956  [0.012820512987673283, 0.04700854793190956, 0....   
386957  [0.11594203114509583, 0.4202898442745209, 0.04...   
386958  [0.011019283905625343, 0.8622589707374573, 0.0...   

                                                 coverage  \
0                                              [0.5, 0.5]   
1                     [0.5, 0.25, 0.25, 0.75, 0.25, 0.25]   
2       [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,...   
3                                                  [0.75]   
4       [0.5, 0.75, 0.25, 1.0, 0.5, 0.75, 1.0, 0.5, 0....   
...                                                   ...   
386954  [0.5, 0.25, 0.25, 1.0, 1.0, 0.75, 0.5, 0.25, 1...   
386955  [0.25, 0.5, 0.75, 1.0, 0.75, 1.0, 1.0, 0.25, 0...   
386956  [0.25, 0.5, 0.25, 1.0, 1.0, 0.75, 1.0, 0.75, 0...   
386957  [0.5, 0.5, 0.25, 0.25, 1.0, 0.5, 0.25, 0.5, 1....   
386958  [0.5, 1.0, 0.75, 0.75, 1.0, 0.5, 0.75, 1.0, 1....   

                                                   values  
0                                             [48.0, 7.0]  
1                     [32.0, 32.0, 23.0, 32.0, 7.0, 23.0]  
2       [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....  
3                                                  [23.0]  
4       [35.0, 10.0, 35.0, 35.0, 6.0, 4.0, 35.0, 10.0,...  
...                                                   ...  
386954  [31.0, 31.0, 3.0, 48.0, 48.0, 31.0, 31.0, 3.0,...  
386955  [35.0, 4.0, 35.0, 35.0, 10.0, 19.0, 10.0, 35.0...  
386956  [48.0, 4.0, 4.0, 48.0, 10.0, 48.0, 10.0, 10.0,...  
386957  [10.0, 10.0, 10.0, 48.0, 23.0, 10.0, 48.0, 10....  
386958  [48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48....  

[386959 rows x 5 columns]

In [35]:
result.loc[:,['coverage', 'values']]

coverage  \
0                                              [0.5, 0.5]   
1                     [0.5, 0.25, 0.25, 0.75, 0.25, 0.25]   
2       [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,...   
3                                                  [0.75]   
4       [0.5, 0.75, 0.25, 1.0, 0.5, 0.75, 1.0, 0.5, 0....   
...                                                   ...   
386954  [0.5, 0.25, 0.25, 1.0, 1.0, 0.75, 0.5, 0.25, 1...   
386955  [0.25, 0.5, 0.75, 1.0, 0.75, 1.0, 1.0, 0.25, 0...   
386956  [0.25, 0.5, 0.25, 1.0, 1.0, 0.75, 1.0, 0.75, 0...   
386957  [0.5, 0.5, 0.25, 0.25, 1.0, 0.5, 0.25, 0.5, 1....   
386958  [0.5, 1.0, 0.75, 0.75, 1.0, 0.5, 0.75, 1.0, 1....   

                                                   values  
0                                             [48.0, 7.0]  
1                     [32.0, 32.0, 23.0, 32.0, 7.0, 23.0]  
2       [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....  
3                                                  [23.0]  
4       [35.0, 10.0, 35.0, 35.0, 6.0, 4.0, 35.0, 10.0,...  
...                                                   ...  
386954  [31.0, 31.0, 3.0, 48.0, 48.0, 31.0, 31.0, 3.0,...  
386955  [35.0, 4.0, 35.0, 35.0, 10.0, 19.0, 10.0, 35.0...  
386956  [48.0, 4.0, 4.0, 48.0, 10.0, 48.0, 10.0, 10.0,...  
386957  [10.0, 10.0, 10.0, 48.0, 23.0, 10.0, 48.0, 10....  
386958  [48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48....  

[386959 rows x 2 columns]

In [13]:
result.iloc[2]

gid                                                15243650.0
majority                                                 10.0
frac        [0.06923077255487442, 0.7153846025466919, 0.02...
coverage    [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,...
values      [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....
Name: 2, dtype: object

In [14]:
result.iloc[2].coverage

array([0.25, 0.5 , 0.5 , 0.5 , 0.5 , 1.  , 1.  , 1.  , 1.  , 1.  , 0.25,
       0.5 , 1.  , 1.  , 1.  , 1.  , 1.  , 0.5 , 0.5 , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 0.25, 0.75, 1.  , 1.  , 1.  , 1.  , 1.  , 0.5 ,
       0.25, 1.  , 1.  , 1.  , 0.75, 0.5 , 1.  , 0.5 ])

In [16]:
result.iloc[2]["values"]

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,  7., 10., 10.,
       10., 10., 10.,  7., 10., 10.,  4., 10., 10., 10., 10., 10., 10.,
       35., 48., 10., 10.,  4., 10., 10., 10., 48.,  7., 10.,  8., 13.,
        4., 10.])

In [18]:
label_id = result.iloc[2]["values"]
fraction_values = result.iloc[2].coverage

# Create a dictionary to store the sum for each unique label_id
sum_per_label = {}

# Iterate through unique label_id values
unique_labels = np.unique(label_id)
for label in unique_labels:
    # Filter fraction_values based on the current label_id
    values_for_label = fraction_values[label_id == label]
    
    # Calculate the sum and store it in the dictionary
    sum_per_label[label] = np.sum(values_for_label)

# Print the result
for label, total_sum in sum_per_label.items():
    print(f"Label {label}: Sum = {total_sum}")

Label 4.0: Sum = 3.0
Label 7.0: Sum = 2.25
Label 8.0: Sum = 0.75
Label 10.0: Sum = 23.25
Label 13.0: Sum = 0.5
Label 35.0: Sum = 0.75
Label 48.0: Sum = 2.0


In [26]:
np.array(list(sum_per_label.values())).sum()

32.5

In [31]:
print(sum_per_label.keys())
print(np.array(list(sum_per_label.values())) / np.array(list(sum_per_label.values())).sum())

dict_keys([4.0, 7.0, 8.0, 10.0, 13.0, 35.0, 48.0])
[0.09230769 0.06923077 0.02307692 0.71538462 0.01538462 0.02307692
 0.06153846]


In [12]:
result.iloc[2].frac

array([0.06923077, 0.7153846 , 0.02307692, 0.06153846, 0.09230769,
       0.02307692, 0.01538462])

In [69]:
# Function to calculate sum_per_label and unique_label_desc
def calculate_sums(row):
    label_id = np.array(row['values']).flatten()
    fraction_values = np.array(row['coverage']).flatten()
    
    # Create a dictionary to store the sum for each unique label_id
    sum_per_label = {}
    
    # Iterate through unique label_id values
    unique_labels = np.unique(label_id)
    for label in unique_labels:
        # Filter fraction_values based on the current label_id
        values_for_label = fraction_values[label_id == label]
        
        # Calculate the sum and store it in the dictionary
        sum_per_label[label] = np.sum(values_for_label)
    
    # Sort sum_per_label and create a string with unique labels sorted by descending order
    sorted_sum_per_label = {k: v for k, v in sorted(sum_per_label.items(), key=lambda item: item[1], reverse=True)}
    unique_label_desc = ', '.join(map(str, sorted_sum_per_label.keys()))
    
    # Update the row with the calculated values
    row['sum_per_label'] = sorted_sum_per_label
    row['unique_label_desc'] = unique_label_desc
    
    return row

In [63]:
# Sample DataFrame
data = {'coverage': [[0.5, 0.5], 
                     [0.5, 0.25, 0.25, 0.75, 0.25, 0.25], 
                     [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0], 
                     [0.75], 
                     [0.5, 0.75, 0.25, 1.0, 0.5, 0.75, 1.0, 0.5, 0.75]],
        'values': [[48.0, 7.0], 
                   [32.0, 32.0, 23.0, 32.0, 7.0, 23.0], 
                   [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0], 
                   [23.0], 
                   [35.0, 10.0, 35.0, 35.0, 6.0, 4.0, 35.0, 10.0, 6.0]]}

df = pd.DataFrame(data)

In [64]:
df_new = df.apply(calculate_sums, axis=1)
df_new

coverage  \
0                                         [0.5, 0.5]   
1                [0.5, 0.25, 0.25, 0.75, 0.25, 0.25]   
2     [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0]   
3                                             [0.75]   
4  [0.5, 0.75, 0.25, 1.0, 0.5, 0.75, 1.0, 0.5, 0.75]   

                                              values  \
0                                        [48.0, 7.0]   
1                [32.0, 32.0, 23.0, 32.0, 7.0, 23.0]   
2  [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....   
3                                             [23.0]   
4  [35.0, 10.0, 35.0, 35.0, 6.0, 4.0, 35.0, 10.0,...   

                                    sum_per_label     unique_label_desc  
0                           {7.0: 0.5, 48.0: 0.5}             7.0, 48.0  
1               {32.0: 1.5, 23.0: 0.5, 7.0: 0.25}       32.0, 23.0, 7.0  
2                                    {10.0: 6.25}                  10.0  
3                                    {23.0: 0.75}                  23.0  
4  {35.0: 2.75, 6.0: 1.25, 10.0: 1.25, 4.0: 0.75}  35.0, 6.0, 10.0, 4.0

In [68]:
%%timeit
results_new = result.iloc[:1000].apply(calculate_sums, axis=1)
results_new

1.22 s ± 11.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [79]:
%%timeit
def calculate_sums_vectorized(row):
    label_id = pd.Series(row['values'])
    fraction_values = pd.Series(row['coverage'])
    
    # Calculate the sum for each unique label_id using vectorized operations
    sum_per_label = fraction_values.groupby(label_id).sum().sort_values(ascending=False)
    
    # Create a string of the unique labels sorted by descending order
    unique_label_desc = ', '.join(map(str, sum_per_label.index))
    
    # Update the row with the calculated values
    row['sum_per_label'] = sum_per_label.to_dict()
    row['unique_label_desc'] = unique_label_desc
    
    return row

rresults_new = result.iloc[:1000].apply(calculate_sums_vectorized, axis=1)

1.74 s ± 30.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [84]:
from joblib import Parallel, delayed
from tqdm import tqdm

# Define the number of cores to use for parallel processing
n_jobs = 16

# Apply the function to each row using parallel processing
df_new = Parallel(n_jobs=n_jobs)(delayed(calculate_sums)(row) for _, row in tqdm(result.iterrows()))

# Convert the list of rows back to a DataFrame
df_new = pd.DataFrame(df_new)

0it [00:00, ?it/s]

386959it [03:46, 1709.94it/s]


In [85]:
df_new

gid  majority  \
0       15320461.0      48.0   
1       15029785.0      32.0   
2       15243650.0      10.0   
3       15322602.0      23.0   
4       15321453.0      35.0   
...            ...       ...   
386954  15271767.0      31.0   
386955  15038183.0      10.0   
386956  15179203.0      10.0   
386957  15038343.0      10.0   
386958  15319521.0      48.0   

                                                     frac  \
0                                              [0.5, 0.5]   
1       [0.6666666865348816, 0.2222222238779068, 0.111...   
2       [0.06923077255487442, 0.7153846025466919, 0.02...   
3                                                   [1.0]   
4       [0.6388888955116272, 0.1666666716337204, 0.083...   
...                                                   ...   
386954  [0.022727273404598236, 0.3579545319080353, 0.0...   
386955  [0.1015625, 0.03125, 0.078125, 0.171875, 0.226...   
386956  [0.012820512987673283, 0.04700854793190956, 0....   
386957  [0.11594203114509583, 0.4202898442745209, 0.04...   
386958  [0.011019283905625343, 0.8622589707374573, 0.0...   

                                                 coverage  \
0                                              [0.5, 0.5]   
1                     [0.5, 0.25, 0.25, 0.75, 0.25, 0.25]   
2       [0.25, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,...   
3                                                  [0.75]   
4       [0.5, 0.75, 0.25, 1.0, 0.5, 0.75, 1.0, 0.5, 0....   
...                                                   ...   
386954  [0.5, 0.25, 0.25, 1.0, 1.0, 0.75, 0.5, 0.25, 1...   
386955  [0.25, 0.5, 0.75, 1.0, 0.75, 1.0, 1.0, 0.25, 0...   
386956  [0.25, 0.5, 0.25, 1.0, 1.0, 0.75, 1.0, 0.75, 0...   
386957  [0.5, 0.5, 0.25, 0.25, 1.0, 0.5, 0.25, 0.5, 1....   
386958  [0.5, 1.0, 0.75, 0.75, 1.0, 0.5, 0.75, 1.0, 1....   

                                                   values  \
0                                             [48.0, 7.0]   
1                     [32.0, 32.0, 23.0, 32.0, 7.0, 23.0]   
2       [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....   
3                                                  [23.0]   
4       [35.0, 10.0, 35.0, 35.0, 6.0, 4.0, 35.0, 10.0,...   
...                                                   ...   
386954  [31.0, 31.0, 3.0, 48.0, 48.0, 31.0, 31.0, 3.0,...   
386955  [35.0, 4.0, 35.0, 35.0, 10.0, 19.0, 10.0, 35.0...   
386956  [48.0, 4.0, 4.0, 48.0, 10.0, 48.0, 10.0, 10.0,...   
386957  [10.0, 10.0, 10.0, 48.0, 23.0, 10.0, 48.0, 10....   
386958  [48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48.0, 48....   

                                            sum_per_label  \
0                                   {7.0: 0.5, 48.0: 0.5}   
1                       {32.0: 1.5, 23.0: 0.5, 7.0: 0.25}   
2       {10.0: 23.25, 4.0: 3.0, 7.0: 2.25, 48.0: 2.0, ...   
3                                            {23.0: 0.75}   
4            {35.0: 5.75, 10.0: 1.5, 6.0: 1.0, 4.0: 0.75}   
...                                                   ...   
386954  {31.0: 15.75, 32.0: 10.5, 10.0: 10.0, 48.0: 3....   
386955  {10.0: 7.25, 4.0: 5.5, 35.0: 3.25, 8.0: 2.5, 3...   
386956  {10.0: 37.25, 7.0: 10.5, 13.0: 4.5, 35.0: 2.75...   
386957  {10.0: 14.5, 23.0: 8.75, 7.0: 4.0, 48.0: 2.5, ...   
386958  {48.0: 78.25, 13.0: 4.0, 7.0: 3.0, 23.0: 2.5, ...   

                                        unique_label_desc  
0                                               7.0, 48.0  
1                                         32.0, 23.0, 7.0  
2                   10.0, 4.0, 7.0, 48.0, 8.0, 35.0, 13.0  
3                                                    23.0  
4                                    35.0, 10.0, 6.0, 4.0  
...                                                   ...  
386954        31.0, 32.0, 10.0, 48.0, 7.0, 3.0, 23.0, 8.0  
386955  10.0, 4.0, 35.0, 8.0, 38.0, 18.0, 36.0, 19.0, ...  
386956                   10.0, 7.0, 13.0, 35.0, 48.0, 4.0  
386957  10.0, 23.0, 7.0, 48.0, 32.0, 13.0, 22.0, 31.0,...  
386958                   48.0, 13.0, 7